package org.talend.designer.codegen.translators.data_quality.address;

import org.talend.core.model.metadata.IMetadataColumn;
import org.talend.core.model.process.ElementParameterParser;
import org.talend.core.model.process.IConnection;
import org.talend.core.model.process.IConnectionCategory;
import org.talend.core.model.process.INode;
import org.talend.designer.codegen.config.CodeGeneratorArgument;
import java.util.List;

public class TGoogleAddressRowMainJava
{
  protected static String nl;
  public static synchronized TGoogleAddressRowMainJava create(String lineSeparator)
  {
    nl = lineSeparator;
    TGoogleAddressRowMainJava result = new TGoogleAddressRowMainJava();
    nl = null;
    return result;
  }

  public final String NL = nl == null ? (System.getProperties().getProperty("line.separator")) : nl;
  protected final String TEXT_1 = "";
  protected final String TEXT_2 = NL + "if(";
  protected final String TEXT_3 = " == null || \"\".equals(";
  protected final String TEXT_4 = ".trim())) {" + NL + "    System.err.println(\"[ERROR]: Please make sure all the tGoogleAddressRow components have input the API key.\");" + NL + "    return;" + NL + "}";
  protected final String TEXT_5 = " " + NL + "        String saddress_";
  protected final String TEXT_6 = "  = ";
  protected final String TEXT_7 = ".";
  protected final String TEXT_8 = ";" + NL + "        javax.xml.xpath.XPath xPath1_";
  protected final String TEXT_9 = " = javax.xml.xpath.XPathFactory.newInstance().newXPath();" + NL + "        org.w3c.dom.Document response1_";
  protected final String TEXT_10 = " = null;" + NL + "        String status1_";
  protected final String TEXT_11 = "=null;" + NL + "        try{" + NL + "            // Send GET request" + NL + "            String url1_";
  protected final String TEXT_12 = " =\"https://maps.googleapis.com/maps/api/place/textsearch/xml?query=\"+java.net.URLEncoder.encode(saddress_";
  protected final String TEXT_13 = " , utf8Charset)+\"&sensor=false&key=\"+";
  protected final String TEXT_14 = ".trim();" + NL + "" + NL + "            java.net.URL client1_";
  protected final String TEXT_15 = " = new java.net.URL(url1_";
  protected final String TEXT_16 = ");" + NL + "            java.net.URLConnection conn1_";
  protected final String TEXT_17 = " = client1_";
  protected final String TEXT_18 = ".openConnection();" + NL + "            Thread.sleep((";
  protected final String TEXT_19 = ")*100);" + NL + "            java.io.InputStream responseBody1_";
  protected final String TEXT_20 = " = conn1_";
  protected final String TEXT_21 = ".getInputStream();" + NL + "            " + NL + "            // XML Bufferization" + NL + "            response1_";
  protected final String TEXT_22 = " = javax.xml.parsers.DocumentBuilderFactory.newInstance().newDocumentBuilder().parse(responseBody1_";
  protected final String TEXT_23 = ");" + NL + "            responseBody1_";
  protected final String TEXT_24 = ".close();" + NL + "            " + NL + "            status1_";
  protected final String TEXT_25 = "=xPath1_";
  protected final String TEXT_26 = ".evaluate(\"/PlaceSearchResponse/status\", response1_";
  protected final String TEXT_27 = ");" + NL + "            " + NL + "        }catch(IOException  e_";
  protected final String TEXT_28 = "){";
  protected final String TEXT_29 = NL + "                throw e_";
  protected final String TEXT_30 = ";";
  protected final String TEXT_31 = NL + "                System.err.println(e_";
  protected final String TEXT_32 = ".getMessage());";
  protected final String TEXT_33 = NL + "        }" + NL;
  protected final String TEXT_34 = "              ";
  protected final String TEXT_35 = NL + "                ";
  protected final String TEXT_36 = " = new ";
  protected final String TEXT_37 = "Struct();" + NL + "                " + NL + "                if(\"OK\".equals(status1_";
  protected final String TEXT_38 = ")) {" + NL + "                    javax.xml.xpath.XPath xPath2_";
  protected final String TEXT_39 = " = javax.xml.xpath.XPathFactory.newInstance().newXPath();" + NL + "                    org.w3c.dom.Document response2_";
  protected final String TEXT_40 = " = null;" + NL + "                    String status2_";
  protected final String TEXT_41 = " = null;" + NL + "                    try{" + NL + "                        String placeid_";
  protected final String TEXT_42 = "=xPath1_";
  protected final String TEXT_43 = ".evaluate(\"/PlaceSearchResponse/result[1]/place_id\", response1_";
  protected final String TEXT_44 = ");" + NL + "                        // Send GET request" + NL + "                        String url2_";
  protected final String TEXT_45 = " =\"https://maps.googleapis.com/maps/api/place/details/xml?placeid=\"+placeid_";
  protected final String TEXT_46 = "+\"&key=\"+";
  protected final String TEXT_47 = ".trim();" + NL + "                " + NL + "                        java.net.URL client2_";
  protected final String TEXT_48 = " = new java.net.URL(url2_";
  protected final String TEXT_49 = ");" + NL + "                        java.net.URLConnection conn2_";
  protected final String TEXT_50 = " = client2_";
  protected final String TEXT_51 = ".openConnection();" + NL + "                        Thread.sleep((";
  protected final String TEXT_52 = ")*100);" + NL + "                        java.io.InputStream responseBody2_";
  protected final String TEXT_53 = " = conn2_";
  protected final String TEXT_54 = ".getInputStream();" + NL + "                        " + NL + "                        // XML Bufferization" + NL + "                        response2_";
  protected final String TEXT_55 = " = javax.xml.parsers.DocumentBuilderFactory.newInstance().newDocumentBuilder().parse(responseBody2_";
  protected final String TEXT_56 = ");" + NL + "                        responseBody2_";
  protected final String TEXT_57 = ".close();" + NL + "                       " + NL + "                        status2_";
  protected final String TEXT_58 = "=xPath2_";
  protected final String TEXT_59 = ".evaluate(\"/PlaceDetailsResponse/status\", response2_";
  protected final String TEXT_60 = ");" + NL + "                    }catch(IOException  e_";
  protected final String TEXT_61 = "){";
  protected final String TEXT_62 = "              " + NL + "                            throw e_";
  protected final String TEXT_63 = ";";
  protected final String TEXT_64 = "              " + NL + "                            System.err.println(e_";
  protected final String TEXT_65 = ".getMessage());";
  protected final String TEXT_66 = "              " + NL + "                    }" + NL + "" + NL + "                    if(\"OK\".equals(status2_";
  protected final String TEXT_67 = ")) {";
  protected final String TEXT_68 = NL + "                        ";
  protected final String TEXT_69 = ".street_number_long = xPath2_";
  protected final String TEXT_70 = ".evaluate(\"/PlaceDetailsResponse/result[1]/address_component[type/text()='street_number']/long_name\", response2_";
  protected final String TEXT_71 = ");";
  protected final String TEXT_72 = NL + "                        ";
  protected final String TEXT_73 = ".street_number_short = xPath2_";
  protected final String TEXT_74 = ".evaluate(\"/PlaceDetailsResponse/result[1]/address_component[type/text()='street_number']/short_name\", response2_";
  protected final String TEXT_75 = ");" + NL + "                      ";
  protected final String TEXT_76 = NL + "                        ";
  protected final String TEXT_77 = ".route_short =xPath2_";
  protected final String TEXT_78 = ".evaluate(\"/PlaceDetailsResponse/result[1]/address_component[type/text()='route']/short_name\", response2_";
  protected final String TEXT_79 = ");";
  protected final String TEXT_80 = NL + "                        ";
  protected final String TEXT_81 = ".route_long =xPath2_";
  protected final String TEXT_82 = ".evaluate(\"/PlaceDetailsResponse/result[1]/address_component[type/text()='route']/long_name\", response2_";
  protected final String TEXT_83 = ");" + NL + "                      " + NL + "                      ";
  protected final String TEXT_84 = NL + "                        ";
  protected final String TEXT_85 = ".locality_short=xPath2_";
  protected final String TEXT_86 = ".evaluate(\"/PlaceDetailsResponse/result[1]/address_component[type/text()='locality']/short_name\", response2_";
  protected final String TEXT_87 = ");";
  protected final String TEXT_88 = NL + "                        ";
  protected final String TEXT_89 = ".locality_long=xPath2_";
  protected final String TEXT_90 = ".evaluate(\"/PlaceDetailsResponse/result[1]/address_component[type/text()='locality']/long_name\", response2_";
  protected final String TEXT_91 = ");" + NL + "                      ";
  protected final String TEXT_92 = NL + "                        ";
  protected final String TEXT_93 = ".sublocality_short=xPath2_";
  protected final String TEXT_94 = ".evaluate(\"/PlaceDetailsResponse/result[1]/address_component[type/text()='sublocality']/short_name\", response2_";
  protected final String TEXT_95 = ");";
  protected final String TEXT_96 = NL + "                        ";
  protected final String TEXT_97 = ".sublocality_long=xPath2_";
  protected final String TEXT_98 = ".evaluate(\"/PlaceDetailsResponse/result[1]/address_component[type/text()='sublocality']/long_name\", response2_";
  protected final String TEXT_99 = ");" + NL + "                      ";
  protected final String TEXT_100 = NL + "                        ";
  protected final String TEXT_101 = ".adm_area1_short=xPath2_";
  protected final String TEXT_102 = ".evaluate(\"/PlaceDetailsResponse/result[1]/address_component[type/text()='administrative_area_level_1']/short_name\", response2_";
  protected final String TEXT_103 = ");";
  protected final String TEXT_104 = NL + "                        ";
  protected final String TEXT_105 = ".adm_area1_long=xPath2_";
  protected final String TEXT_106 = ".evaluate(\"/PlaceDetailsResponse/result[1]/address_component[type/text()='administrative_area_level_1']/long_name\", response2_";
  protected final String TEXT_107 = ");" + NL + "                      ";
  protected final String TEXT_108 = NL + "                        ";
  protected final String TEXT_109 = ".adm_area2_short=xPath2_";
  protected final String TEXT_110 = ".evaluate(\"/PlaceDetailsResponse/result[1]/address_component[type/text()='administrative_area_level_2']/short_name\", response2_";
  protected final String TEXT_111 = ");";
  protected final String TEXT_112 = NL + "                        ";
  protected final String TEXT_113 = ".adm_area2_long=xPath2_";
  protected final String TEXT_114 = ".evaluate(\"/PlaceDetailsResponse/result[1]/address_component[type/text()='administrative_area_level_2']/long_name\", response2_";
  protected final String TEXT_115 = ");" + NL + "                      ";
  protected final String TEXT_116 = NL + "                        ";
  protected final String TEXT_117 = ".adm_area3_short=xPath2_";
  protected final String TEXT_118 = ".evaluate(\"/PlaceDetailsResponse/result[1]/address_component[type/text()='administrative_area_level_3']/short_name\", response2_";
  protected final String TEXT_119 = ");";
  protected final String TEXT_120 = NL + "                        ";
  protected final String TEXT_121 = ".adm_area3_long=xPath2_";
  protected final String TEXT_122 = ".evaluate(\"/PlaceDetailsResponse/result[1]/address_component[type/text()='administrative_area_level_3']/long_name\", response2_";
  protected final String TEXT_123 = ");" + NL + "                      ";
  protected final String TEXT_124 = NL + "                        ";
  protected final String TEXT_125 = ".country_short=xPath2_";
  protected final String TEXT_126 = ".evaluate(\"/PlaceDetailsResponse/result[1]/address_component[type/text()='country']/short_name\", response2_";
  protected final String TEXT_127 = ");";
  protected final String TEXT_128 = NL + "                        ";
  protected final String TEXT_129 = ".country_long=xPath2_";
  protected final String TEXT_130 = ".evaluate(\"/PlaceDetailsResponse/result[1]/address_component[type/text()='country']/long_name\", response2_";
  protected final String TEXT_131 = ");" + NL + "                      ";
  protected final String TEXT_132 = NL + "                        ";
  protected final String TEXT_133 = ".postal_code_short=xPath2_";
  protected final String TEXT_134 = ".evaluate(\"/PlaceDetailsResponse/result[1]/address_component[type/text()='postal_code']/short_name\", response2_";
  protected final String TEXT_135 = ");";
  protected final String TEXT_136 = NL + "                        ";
  protected final String TEXT_137 = ".postal_code_long=xPath2_";
  protected final String TEXT_138 = ".evaluate(\"/PlaceDetailsResponse/result[1]/address_component[type/text()='postal_code']/long_name\", response2_";
  protected final String TEXT_139 = ");" + NL + "                      ";
  protected final String TEXT_140 = NL + "                        ";
  protected final String TEXT_141 = ".location_type=xPath2_";
  protected final String TEXT_142 = ".evaluate(\"/PlaceDetailsResponse/result[1]/type\", response2_";
  protected final String TEXT_143 = ");";
  protected final String TEXT_144 = NL + "                        ";
  protected final String TEXT_145 = ".partial_match=\"\";" + NL + "                      ";
  protected final String TEXT_146 = NL + "                        ";
  protected final String TEXT_147 = ".lat=Double.parseDouble(\"\" + xPath2_";
  protected final String TEXT_148 = ".evaluate(\"/PlaceDetailsResponse/result[1]/geometry/location/lat\", response2_";
  protected final String TEXT_149 = "));";
  protected final String TEXT_150 = NL + "                        ";
  protected final String TEXT_151 = ".lng=Double.parseDouble(\"\" + xPath2_";
  protected final String TEXT_152 = ".evaluate(\"/PlaceDetailsResponse/result[1]/geometry/location/lng\", response2_";
  protected final String TEXT_153 = "));";
  protected final String TEXT_154 = NL + "                        ";
  protected final String TEXT_155 = ".formatted_address=xPath2_";
  protected final String TEXT_156 = ".evaluate(\"/PlaceDetailsResponse/result[1]/formatted_address\", response2_";
  protected final String TEXT_157 = ");" + NL + "                    } else if(\"REQUEST_DENIED\".equals(status2_";
  protected final String TEXT_158 = ")  || status2_";
  protected final String TEXT_159 = ".equals(\"OVER_QUERY_LIMIT\")) {" + NL + "                        System.err.println(status2_";
  protected final String TEXT_160 = " + \": \" + xPath2_";
  protected final String TEXT_161 = ".evaluate(\"/PlaceDetailsResponse/error_message\", response2_";
  protected final String TEXT_162 = "));" + NL + "                        return;" + NL + "                    }";
  protected final String TEXT_163 = NL + "                    ";
  protected final String TEXT_164 = ".status=status2_";
  protected final String TEXT_165 = ";";
  protected final String TEXT_166 = "                      ";
  protected final String TEXT_167 = NL + "                            ";
  protected final String TEXT_168 = ".";
  protected final String TEXT_169 = " = ";
  protected final String TEXT_170 = ".";
  protected final String TEXT_171 = ";";
  protected final String TEXT_172 = NL + "                } else if(\"ZERO_RESULTS\".equals(status1_";
  protected final String TEXT_173 = ") || \"INVALID_REQUEST\".equals(status1_";
  protected final String TEXT_174 = ")) {";
  protected final String TEXT_175 = NL + "                    ";
  protected final String TEXT_176 = ".status=status1_";
  protected final String TEXT_177 = ";";
  protected final String TEXT_178 = NL + "                    ";
  protected final String TEXT_179 = ".street_number_long = \"\";";
  protected final String TEXT_180 = NL + "                    ";
  protected final String TEXT_181 = ".street_number_short = \"\";" + NL + "                  ";
  protected final String TEXT_182 = NL + "                    ";
  protected final String TEXT_183 = ".route_short = \"\";";
  protected final String TEXT_184 = NL + "                    ";
  protected final String TEXT_185 = ".route_long = \"\";" + NL + "                  " + NL + "                  ";
  protected final String TEXT_186 = NL + "                    ";
  protected final String TEXT_187 = ".locality_short= \"\";";
  protected final String TEXT_188 = NL + "                    ";
  protected final String TEXT_189 = ".locality_long= \"\";" + NL + "                  ";
  protected final String TEXT_190 = NL + "                    ";
  protected final String TEXT_191 = ".sublocality_short= \"\";";
  protected final String TEXT_192 = NL + "                    ";
  protected final String TEXT_193 = ".sublocality_long= \"\";" + NL + "                  ";
  protected final String TEXT_194 = NL + "                    ";
  protected final String TEXT_195 = ".adm_area1_short= \"\";";
  protected final String TEXT_196 = NL + "                    ";
  protected final String TEXT_197 = ".adm_area1_long= \"\";" + NL + "                  ";
  protected final String TEXT_198 = NL + "                    ";
  protected final String TEXT_199 = ".adm_area2_short= \"\";";
  protected final String TEXT_200 = NL + "                    ";
  protected final String TEXT_201 = ".adm_area2_long= \"\";" + NL + "                  ";
  protected final String TEXT_202 = NL + "                    ";
  protected final String TEXT_203 = ".adm_area3_short= \"\";";
  protected final String TEXT_204 = NL + "                    ";
  protected final String TEXT_205 = ".adm_area3_long= \"\";" + NL + "                  ";
  protected final String TEXT_206 = NL + "                    ";
  protected final String TEXT_207 = ".country_short= \"\";";
  protected final String TEXT_208 = NL + "                    ";
  protected final String TEXT_209 = ".country_long= \"\";" + NL + "                  ";
  protected final String TEXT_210 = NL + "                    ";
  protected final String TEXT_211 = ".postal_code_short= \"\";";
  protected final String TEXT_212 = NL + "                    ";
  protected final String TEXT_213 = ".postal_code_long= \"\";" + NL + "                  ";
  protected final String TEXT_214 = NL + "                    ";
  protected final String TEXT_215 = ".location_type= \"\";";
  protected final String TEXT_216 = NL + "                    ";
  protected final String TEXT_217 = ".partial_match= \"\";" + NL + "                  ";
  protected final String TEXT_218 = NL + "                    ";
  protected final String TEXT_219 = ".lat= Double.parseDouble(\"0\");";
  protected final String TEXT_220 = NL + "                    ";
  protected final String TEXT_221 = ".lng= Double.parseDouble(\"0\");";
  protected final String TEXT_222 = NL + "                    ";
  protected final String TEXT_223 = ".formatted_address= \"\";" + NL + "                } else if(\"REQUEST_DENIED\".equals(status1_";
  protected final String TEXT_224 = ") || \"OVER_QUERY_LIMIT\".equals(status1_";
  protected final String TEXT_225 = ")) {" + NL + "                    System.err.println(status1_";
  protected final String TEXT_226 = " + \": \" + xPath1_";
  protected final String TEXT_227 = ".evaluate(\"/PlaceSearchResponse/error_message\", response1_";
  protected final String TEXT_228 = "));" + NL + "                    return;" + NL + "                }" + NL + "                ";
  protected final String TEXT_229 = NL + "                        ";
  protected final String TEXT_230 = ".";
  protected final String TEXT_231 = " = ";
  protected final String TEXT_232 = ".";
  protected final String TEXT_233 = ";";

  public String generate(Object argument)
  {
    final StringBuffer stringBuffer = new StringBuffer();
    stringBuffer.append(TEXT_1);
    
CodeGeneratorArgument codeGenArgument = (CodeGeneratorArgument) argument;
INode node = (INode)codeGenArgument.getArgument();
String cid = node.getUniqueName();
String inConnName = null;
String apiKey = ElementParameterParser.getValue(node, "__API_KEY__"); 

    stringBuffer.append(TEXT_2);
    stringBuffer.append( apiKey );
    stringBuffer.append(TEXT_3);
    stringBuffer.append( apiKey );
    stringBuffer.append(TEXT_4);
    

List<? extends IConnection> inConns = node.getIncomingConnections();
List<? extends IConnection> outConns = node.getOutgoingConnections();
IConnection inConn = null;
if(inConns != null && inConns.size() > 0) {
    for (IConnection conn: inConns) {
        if (conn.getLineStyle().hasConnectionCategory(IConnectionCategory.DATA)) {
            inConn = conn;
            inConnName = inConn.getName();
            break;
        }
    }
}
if(inConn!=null){
    List<IMetadataColumn> columnList = inConn.getMetadataTable().getListColumns();
    String pause = ElementParameterParser.getValue(node, "__PAUSE__");
    if(inConnName != null && columnList != null && (columnList.size() > 0) ) {
        String ColumnSource = ElementParameterParser.getValue(node, "__ADDRESS_COLUMN__");
        String dieOnErrorStr = ElementParameterParser.getValue(node, "__DIE_ON_ERROR__");
        boolean dieOnError = (dieOnErrorStr!=null&&!("").equals(dieOnErrorStr))?("true").equals(dieOnErrorStr):false; 

    stringBuffer.append(TEXT_5);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_6);
    stringBuffer.append(inConnName);
    stringBuffer.append(TEXT_7);
    stringBuffer.append(ColumnSource );
    stringBuffer.append(TEXT_8);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_9);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_10);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_11);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_12);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_13);
    stringBuffer.append( apiKey );
    stringBuffer.append(TEXT_14);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_15);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_16);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_17);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_18);
    stringBuffer.append(pause);
    stringBuffer.append(TEXT_19);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_20);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_21);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_22);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_23);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_24);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_25);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_26);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_27);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_28);
    
            if(dieOnError) {

    stringBuffer.append(TEXT_29);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_30);
    
            } else { 

    stringBuffer.append(TEXT_31);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_32);
    
            }

    stringBuffer.append(TEXT_33);
     
        for(IConnection conn:outConns){
            if (conn.getLineStyle().hasConnectionCategory(IConnectionCategory.DATA)) {
                IConnection outConn = outConns.get(0);
                String outConnName = outConn.getName();

    stringBuffer.append(TEXT_34);
    stringBuffer.append(TEXT_35);
    stringBuffer.append(outConnName);
    stringBuffer.append(TEXT_36);
    stringBuffer.append(outConnName);
    stringBuffer.append(TEXT_37);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_38);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_39);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_40);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_41);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_42);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_43);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_44);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_45);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_46);
    stringBuffer.append( apiKey );
    stringBuffer.append(TEXT_47);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_48);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_49);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_50);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_51);
    stringBuffer.append(pause);
    stringBuffer.append(TEXT_52);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_53);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_54);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_55);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_56);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_57);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_58);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_59);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_60);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_61);
                  
                        if(dieOnError) {

    stringBuffer.append(TEXT_62);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_63);
                  
                        } else { 

    stringBuffer.append(TEXT_64);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_65);
                  
                        }

    stringBuffer.append(TEXT_66);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_67);
    stringBuffer.append(TEXT_68);
    stringBuffer.append(outConnName);
    stringBuffer.append(TEXT_69);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_70);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_71);
    stringBuffer.append(TEXT_72);
    stringBuffer.append(outConnName);
    stringBuffer.append(TEXT_73);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_74);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_75);
    stringBuffer.append(TEXT_76);
    stringBuffer.append(outConnName);
    stringBuffer.append(TEXT_77);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_78);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_79);
    stringBuffer.append(TEXT_80);
    stringBuffer.append(outConnName);
    stringBuffer.append(TEXT_81);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_82);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_83);
    stringBuffer.append(TEXT_84);
    stringBuffer.append(outConnName);
    stringBuffer.append(TEXT_85);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_86);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_87);
    stringBuffer.append(TEXT_88);
    stringBuffer.append(outConnName);
    stringBuffer.append(TEXT_89);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_90);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_91);
    stringBuffer.append(TEXT_92);
    stringBuffer.append(outConnName);
    stringBuffer.append(TEXT_93);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_94);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_95);
    stringBuffer.append(TEXT_96);
    stringBuffer.append(outConnName);
    stringBuffer.append(TEXT_97);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_98);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_99);
    stringBuffer.append(TEXT_100);
    stringBuffer.append(outConnName);
    stringBuffer.append(TEXT_101);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_102);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_103);
    stringBuffer.append(TEXT_104);
    stringBuffer.append(outConnName);
    stringBuffer.append(TEXT_105);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_106);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_107);
    stringBuffer.append(TEXT_108);
    stringBuffer.append(outConnName);
    stringBuffer.append(TEXT_109);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_110);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_111);
    stringBuffer.append(TEXT_112);
    stringBuffer.append(outConnName);
    stringBuffer.append(TEXT_113);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_114);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_115);
    stringBuffer.append(TEXT_116);
    stringBuffer.append(outConnName);
    stringBuffer.append(TEXT_117);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_118);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_119);
    stringBuffer.append(TEXT_120);
    stringBuffer.append(outConnName);
    stringBuffer.append(TEXT_121);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_122);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_123);
    stringBuffer.append(TEXT_124);
    stringBuffer.append(outConnName);
    stringBuffer.append(TEXT_125);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_126);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_127);
    stringBuffer.append(TEXT_128);
    stringBuffer.append(outConnName);
    stringBuffer.append(TEXT_129);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_130);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_131);
    stringBuffer.append(TEXT_132);
    stringBuffer.append(outConnName);
    stringBuffer.append(TEXT_133);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_134);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_135);
    stringBuffer.append(TEXT_136);
    stringBuffer.append(outConnName);
    stringBuffer.append(TEXT_137);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_138);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_139);
    stringBuffer.append(TEXT_140);
    stringBuffer.append(outConnName);
    stringBuffer.append(TEXT_141);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_142);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_143);
    stringBuffer.append(TEXT_144);
    stringBuffer.append(outConnName);
    stringBuffer.append(TEXT_145);
    stringBuffer.append(TEXT_146);
    stringBuffer.append(outConnName);
    stringBuffer.append(TEXT_147);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_148);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_149);
    stringBuffer.append(TEXT_150);
    stringBuffer.append(outConnName);
    stringBuffer.append(TEXT_151);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_152);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_153);
    stringBuffer.append(TEXT_154);
    stringBuffer.append(outConnName);
    stringBuffer.append(TEXT_155);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_156);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_157);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_158);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_159);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_160);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_161);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_162);
    stringBuffer.append(TEXT_163);
    stringBuffer.append(outConnName);
    stringBuffer.append(TEXT_164);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_165);
                      
                    if (outConnName!=null) {
                        for (IMetadataColumn metadataColumn : columnList) {        

    stringBuffer.append(TEXT_166);
    stringBuffer.append(TEXT_167);
    stringBuffer.append(outConnName);
    stringBuffer.append(TEXT_168);
    stringBuffer.append(metadataColumn.getLabel());
    stringBuffer.append(TEXT_169);
    stringBuffer.append(inConnName);
    stringBuffer.append(TEXT_170);
    stringBuffer.append(metadataColumn.getLabel());
    stringBuffer.append(TEXT_171);
                          
                        } 
                    }

    stringBuffer.append(TEXT_172);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_173);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_174);
    stringBuffer.append(TEXT_175);
    stringBuffer.append(outConnName);
    stringBuffer.append(TEXT_176);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_177);
    stringBuffer.append(TEXT_178);
    stringBuffer.append(outConnName);
    stringBuffer.append(TEXT_179);
    stringBuffer.append(TEXT_180);
    stringBuffer.append(outConnName);
    stringBuffer.append(TEXT_181);
    stringBuffer.append(TEXT_182);
    stringBuffer.append(outConnName);
    stringBuffer.append(TEXT_183);
    stringBuffer.append(TEXT_184);
    stringBuffer.append(outConnName);
    stringBuffer.append(TEXT_185);
    stringBuffer.append(TEXT_186);
    stringBuffer.append(outConnName);
    stringBuffer.append(TEXT_187);
    stringBuffer.append(TEXT_188);
    stringBuffer.append(outConnName);
    stringBuffer.append(TEXT_189);
    stringBuffer.append(TEXT_190);
    stringBuffer.append(outConnName);
    stringBuffer.append(TEXT_191);
    stringBuffer.append(TEXT_192);
    stringBuffer.append(outConnName);
    stringBuffer.append(TEXT_193);
    stringBuffer.append(TEXT_194);
    stringBuffer.append(outConnName);
    stringBuffer.append(TEXT_195);
    stringBuffer.append(TEXT_196);
    stringBuffer.append(outConnName);
    stringBuffer.append(TEXT_197);
    stringBuffer.append(TEXT_198);
    stringBuffer.append(outConnName);
    stringBuffer.append(TEXT_199);
    stringBuffer.append(TEXT_200);
    stringBuffer.append(outConnName);
    stringBuffer.append(TEXT_201);
    stringBuffer.append(TEXT_202);
    stringBuffer.append(outConnName);
    stringBuffer.append(TEXT_203);
    stringBuffer.append(TEXT_204);
    stringBuffer.append(outConnName);
    stringBuffer.append(TEXT_205);
    stringBuffer.append(TEXT_206);
    stringBuffer.append(outConnName);
    stringBuffer.append(TEXT_207);
    stringBuffer.append(TEXT_208);
    stringBuffer.append(outConnName);
    stringBuffer.append(TEXT_209);
    stringBuffer.append(TEXT_210);
    stringBuffer.append(outConnName);
    stringBuffer.append(TEXT_211);
    stringBuffer.append(TEXT_212);
    stringBuffer.append(outConnName);
    stringBuffer.append(TEXT_213);
    stringBuffer.append(TEXT_214);
    stringBuffer.append(outConnName);
    stringBuffer.append(TEXT_215);
    stringBuffer.append(TEXT_216);
    stringBuffer.append(outConnName);
    stringBuffer.append(TEXT_217);
    stringBuffer.append(TEXT_218);
    stringBuffer.append(outConnName);
    stringBuffer.append(TEXT_219);
    stringBuffer.append(TEXT_220);
    stringBuffer.append(outConnName);
    stringBuffer.append(TEXT_221);
    stringBuffer.append(TEXT_222);
    stringBuffer.append(outConnName);
    stringBuffer.append(TEXT_223);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_224);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_225);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_226);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_227);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_228);
      
                if (outConnName!=null) {
                    for(IMetadataColumn metadataColumn : columnList) {        

    stringBuffer.append(TEXT_229);
    stringBuffer.append(outConnName);
    stringBuffer.append(TEXT_230);
    stringBuffer.append(metadataColumn.getLabel());
    stringBuffer.append(TEXT_231);
    stringBuffer.append(inConnName);
    stringBuffer.append(TEXT_232);
    stringBuffer.append(metadataColumn.getLabel());
    stringBuffer.append(TEXT_233);
    
                    } 
                }
            }
        }

    
    }
}

    return stringBuffer.toString();
  }
}
