package org.talend.designer.codegen.translators.orchestration;

import org.talend.core.model.process.INode;
import org.talend.core.model.process.ElementParameterParser;
import org.talend.core.model.process.IConnection;
import org.talend.designer.codegen.config.CodeGeneratorArgument;
import org.talend.core.model.process.EConnectionType;
import java.util.ArrayList;
import java.util.List;

public class TPartitionerFinallyJava
{
  protected static String nl;
  public static synchronized TPartitionerFinallyJava create(String lineSeparator)
  {
    nl = lineSeparator;
    TPartitionerFinallyJava result = new TPartitionerFinallyJava();
    nl = null;
    return result;
  }

  public final String NL = nl == null ? (System.getProperties().getProperty("line.separator")) : nl;
  protected final String TEXT_1 = "\tif(resourceMap.get(\"finish_";
  protected final String TEXT_2 = "\") == null){" + NL + "\t\tif(resourceMap.get(\"tasks_";
  protected final String TEXT_3 = "\") != null && resourceMap.get(\"futures_";
  protected final String TEXT_4 = "\") != null && resourceMap.get(\"rootEs_";
  protected final String TEXT_5 = "\") != null && resourceMap.get(\"es_";
  protected final String TEXT_6 = "\") != null){" + NL + "\t\t\tjava.util.List<org.talend.concurrent.ParallelTask> tasks_";
  protected final String TEXT_7 = " = (java.util.List<org.talend.concurrent.ParallelTask>)resourceMap.get(\"tasks_";
  protected final String TEXT_8 = "\");" + NL + "\t\t\tjava.util.List<java.util.concurrent.Future<Object>> futures_";
  protected final String TEXT_9 = " = (java.util.List<java.util.concurrent.Future<Object>>)resourceMap.get(\"futures_";
  protected final String TEXT_10 = "\");" + NL + "\t\t\tjava.util.concurrent.ExecutorService rootEs_";
  protected final String TEXT_11 = " = (java.util.concurrent.ExecutorService)resourceMap.get(\"rootEs_";
  protected final String TEXT_12 = "\");" + NL + "\t\t\torg.talend.concurrent.TalendExecutorCompletionService<Object> es_";
  protected final String TEXT_13 = " = (org.talend.concurrent.TalendExecutorCompletionService<Object>)resourceMap.get(\"es_";
  protected final String TEXT_14 = "\");" + NL + "" + NL + "\t\t\tboolean forceShutdown_";
  protected final String TEXT_15 = " = false;" + NL + "\t\t\t" + NL + "\t\t    for (int i_";
  protected final String TEXT_16 = " = 0; i_";
  protected final String TEXT_17 = " < ";
  protected final String TEXT_18 = "; i_";
  protected final String TEXT_19 = "++) {" + NL + "\t\t       tasks_";
  protected final String TEXT_20 = ".get(i_";
  protected final String TEXT_21 = ").makeFinished();" + NL + "\t\t       if (tasks_";
  protected final String TEXT_22 = ".get(i_";
  protected final String TEXT_23 = ").getMap().get(\"HAS_ERROR\") != null) {" + NL + "\t\t       \t\tforceShutdown_";
  protected final String TEXT_24 = " = true;" + NL + "\t\t       \t\tthrow new RuntimeException(\"Exception: \", (Exception)tasks_";
  protected final String TEXT_25 = ".get(i_";
  protected final String TEXT_26 = ").getMap().get(\"HAS_ERROR\"));" + NL + "\t\t       }" + NL + "\t\t       if (tasks_";
  protected final String TEXT_27 = ".get(i_";
  protected final String TEXT_28 = ").getMap().get(\"THREADS_HAVE_ERROR\") != null) {" + NL + "\t\t       \t\tforceShutdown_";
  protected final String TEXT_29 = " = true;" + NL + "\t\t       \t\tglobalMap.put(\"FORCE_SHUTDOWN\",Boolean.TRUE);" + NL + "\t\t       \t\tthrow new RuntimeException(\"Exception\", (Exception)tasks_";
  protected final String TEXT_30 = ".get(i_";
  protected final String TEXT_31 = ").getMap().get(\"THREADS_HAVE_ERROR\"));" + NL + "\t\t       }" + NL + "\t\t    }" + NL + "\t\t    " + NL + "\t\t    for (int i_";
  protected final String TEXT_32 = " = 0; i_";
  protected final String TEXT_33 = " < es_";
  protected final String TEXT_34 = ".size(); i_";
  protected final String TEXT_35 = "++) {" + NL + "\t\t       \tif (tasks_";
  protected final String TEXT_36 = ".get(i_";
  protected final String TEXT_37 = ").getMap().get(\"HAS_ERROR\") != null) {" + NL + "\t\t       \t\tforceShutdown_";
  protected final String TEXT_38 = " = true;" + NL + "\t\t       \t\tthrow new RuntimeException(\"Exception\", (Exception)tasks_";
  protected final String TEXT_39 = ".get(i_";
  protected final String TEXT_40 = ").getMap().get(\"HAS_ERROR\"));" + NL + "\t\t       \t}" + NL + "\t\t       \tif (tasks_";
  protected final String TEXT_41 = ".get(i_";
  protected final String TEXT_42 = ").getMap().get(\"THREADS_HAVE_ERROR\") != null) {" + NL + "\t\t       \t\tforceShutdown_";
  protected final String TEXT_43 = " = true;" + NL + "\t\t       \t\tglobalMap.put(\"FORCE_SHUTDOWN\",Boolean.TRUE);" + NL + "\t\t       \t\tthrow new RuntimeException(\"Exception\", (Exception)tasks_";
  protected final String TEXT_44 = ".get(i_";
  protected final String TEXT_45 = ").getMap().get(\"THREADS_HAVE_ERROR\"));" + NL + "\t\t      \t}" + NL + "\t\t      \tjava.util.Map<String, Object> tmpMap = tasks_";
  protected final String TEXT_46 = ".get(i_";
  protected final String TEXT_47 = ").getMap();" + NL + "\t\t       \tjava.util.Set<String> mapKeys_";
  protected final String TEXT_48 = " = tmpMap.keySet();" + NL + "\t\t       \tfor (String key_";
  protected final String TEXT_49 = " : mapKeys_";
  protected final String TEXT_50 = ") {" + NL + "\t\t       \t\tif (globalMap.get(key_";
  protected final String TEXT_51 = ") == null) {" + NL + "\t\t       \t\t\tglobalMap.put(key_";
  protected final String TEXT_52 = ",tmpMap.get(key_";
  protected final String TEXT_53 = "));" + NL + "\t\t       \t\t} else if (key_";
  protected final String TEXT_54 = ".endsWith(\"NB_LINE\")) {" + NL + "\t\t       \t\t\tInteger val_";
  protected final String TEXT_55 = " = (Integer)tmpMap.get(key_";
  protected final String TEXT_56 = ");" + NL + "\t\t       \t\t\tInteger mval_";
  protected final String TEXT_57 = " = (Integer)globalMap.get(key_";
  protected final String TEXT_58 = ");" + NL + "\t\t       \t\t\tglobalMap.put(key_";
  protected final String TEXT_59 = ",val_";
  protected final String TEXT_60 = "+mval_";
  protected final String TEXT_61 = ");" + NL + "\t\t       \t\t}" + NL + "\t\t       \t}" + NL + "\t\t    }" + NL + "\t\t    if (forceShutdown_";
  protected final String TEXT_62 = ") {" + NL + "\t\t\t    for (java.util.concurrent.Future<Object> f : futures_";
  protected final String TEXT_63 = ") {" + NL + "\t\t\t    \tf.cancel(true);" + NL + "\t\t\t    }" + NL + "\t\t\t    rootEs_";
  protected final String TEXT_64 = ".shutdownNow();" + NL + "\t\t    }else{" + NL + "\t\t    \trootEs_";
  protected final String TEXT_65 = ".shutdown();" + NL + "\t\t    }" + NL + "\t\t}" + NL + "\t}";

  public String generate(Object argument)
  {
    final StringBuffer stringBuffer = new StringBuffer();
    
    CodeGeneratorArgument codeGenArgument = (CodeGeneratorArgument) argument;
    INode node = (INode)codeGenArgument.getArgument();
    String cid = node.getUniqueName();	
    String numPartitions = ElementParameterParser.getValue(node, "__NUM_PARTITIONS__");
    String destinationColl = null;
	int recollTaskCount = 0;
    List<? extends INode> listRecoll= node.getProcess().getNodesOfType("tRecollector");
	if (listRecoll!=null && listRecoll.size() > 0 ) {
		recollTaskCount = listRecoll.size();
	}
   	boolean startRecollector = false;
    List<String> recs = new ArrayList<String>();
    List<? extends IConnection> startsConns = node.getOutgoingConnections(EConnectionType.STARTS);
    for (int i = 0; i < startsConns.size(); i++) {
    	IConnection conn = startsConns.get(i);
    	INode target = conn.getTarget();
    	if (target.getUniqueName().startsWith("tCollector") && destinationColl == null) {
    		destinationColl = target.getUniqueName();
    	} else if (target.getUniqueName().startsWith("tRecollector")) {
    		startRecollector = true;
    		recs.add(target.getUniqueName());
    	}
    }
    boolean isLog4jEnabled = ("true").equals(ElementParameterParser.getValue(node.getProcess(), "__LOG4J_ACTIVATE__"));

    stringBuffer.append(TEXT_1);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_2);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_3);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_4);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_5);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_6);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_7);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_8);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_9);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_10);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_11);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_12);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_13);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_14);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_15);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_16);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_17);
    stringBuffer.append(numPartitions);
    stringBuffer.append(TEXT_18);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_19);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_20);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_21);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_22);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_23);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_24);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_25);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_26);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_27);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_28);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_29);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_30);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_31);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_32);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_33);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_34);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_35);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_36);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_37);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_38);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_39);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_40);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_41);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_42);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_43);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_44);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_45);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_46);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_47);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_48);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_49);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_50);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_51);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_52);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_53);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_54);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_55);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_56);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_57);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_58);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_59);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_60);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_61);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_62);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_63);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_64);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_65);
    return stringBuffer.toString();
  }
}
